export const SET_PRODUCTS ="SET_PRODUCTS";
export const ADD_TO_CART ="ADD_TO_CART";
export const SET_ITEM_QUANTITY ="SET_ITEM_QUANTITY"
export const UPDATE_CART_QUANTITY= "UPDATE_CART_QUANTITY"
export const REMOVE_FROM_CART="REMOVE_FROM_CART;"
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"